### PR TITLE
Create Documentation Portal 

### PR DESCRIPTION
**Pull request by ericpassmore**
Code to make docs.eosnetwork.com pulls docs from various eosnf repos
scripts, documentation, and css styling, react code for docusaurus, and markdown files  
includes doxygen for mandel, mandel.cdt, and mandel-contracts

### CODE REVIEW

**Review by ericpassmore — COMMENTED** [review]
All new files under developer_documentation
With the exception of top level .gitignore and README.md

**Review by ericpassmore — COMMENTED** [review]
Removed duplicate License, main engineering repo already has one
Removed confusing NotesOnInstall.txt better coverage in other docs

**Comment by tedcahalleos** [comment]
> Removed duplicate License, main engineering repo already has one Removed confusing NotesOnInstall.txt better coverage in other docs

I am confused by the "Main engineering repo" comment.  Can you please list the two full paths where the license files were?

**Comment by ericpassmore** [comment]
> > Removed duplicate License, main engineering repo already has one Removed confusing NotesOnInstall.txt better coverage in other docs
> 
> I am confused by the "Main engineering repo" comment. Can you please list the two full paths where the license files were?

Removed engineering/developer_documenation/LICENSE.md 
Unchanged engineering/LICENSE 

I had manually added a license to the newly created subdirectory, which create duplicate license in top level engineering and engineering/developer_documentation

**Comment by ericpassmore** [comment]
closing will move to another separate repository in eosnetworkfoundation

**Pull request closed without merging**
